### ISSUE TITLE
Page title is [object Object]

### ISSUE THREAD

**Issue by jenial** [Automattic/community-translator#2]
When the Community Translator is on, the page title shows up as [object Object] - WordPress.com. We should preserve the original page title.

![_object_object__ _wordpress_com](https://cloud.githubusercontent.com/assets/7637835/12325375/1a567260-baca-11e5-9a7a-6c187acdc9cd.jpg)

**Comment by deBhal** [comment]
I did a bit of digging, and the problem is in the calypso jumpstart, so I've opened the issue there

**Comment by akirk** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/2461
